# Generated by Django 5.0.6 on 2024-07-18 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование населённого пункта')),
                ('slug', models.CharField(blank=True, max_length=60, verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Наименование населённых пунктов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Язык программирования')),
                ('slug', models.CharField(blank=True, max_length=60, verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование вакансии')),
                ('url', models.URLField(unique=True)),
                ('company', models.CharField(max_length=250, verbose_name='Работодатель')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.city', verbose_name='Город')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.language', verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Вакансию',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
