# Generated by Django 5.0.6 on 2024-07-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='address',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Адрес компании'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company_url',
            field=models.URLField(default=None, max_length=250, null=True, verbose_name='Ссылка на фирму'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date_public',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='errors_url',
            field=models.URLField(default=None, max_length=250, null=True, verbose_name='Ошибочный детальный url'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_day',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='Занятость'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='logo_url',
            field=models.URLField(default=None, max_length=250, null=True, verbose_name='Ссылка лого компании'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='site',
            field=models.URLField(default=None, max_length=250, null=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Требования'),
        ),
    ]
