# Generated by Django 5.0.6 on 2024-07-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_rename_timestamp_vacancy_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='timestamps',
        ),
    ]
