# Generated by Django 5.0.6 on 2024-07-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_alter_vacancy_options_vacancy_params_find'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='action',
            field=models.BooleanField(default=True, verbose_name='Действующий'),
        ),
    ]
