# Generated by Django 5.0.6 on 2024-07-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finding', '0004_alter_vacancy_options_vacancy_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='timestamp',
            new_name='timestamps',
        ),
    ]
