# Generated by Django 5.0.6 on 2024-07-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding', '0007_vacancy_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
