# Generated by Django 5.0.6 on 2024-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_options_alter_myuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='action',
            field=models.BooleanField(default=True),
        ),
    ]
