# Generated by Django 5.0.6 on 2024-07-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='action',
        ),
    ]
